/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionfuncionarios;

import com.mycompany.gestionfuncionarios.controller.FuncionarioController;
import com.mycompany.gestionfuncionarios.domain.Funcionario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iud_m
 */
public class Main2 extends javax.swing.JFrame {

    private final FuncionarioController funcionarioController;
    private static final String[] COLUMNS = {"ID", "NOMBRE", "APELLIDO", "TIPO DOCUMENTO", "NUMERO DOCUMENTO", "DIRECCION", "SEXO", "TELEFONO", "FECHA NACIMIENTO", "NIVEL EDUCATIVO"};
    private static final String SELECCIONE = "--------SELECCIONE---------";

    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents();
        txtFuncionarioId.setEditable(false);
        funcionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();
    }

    private void listFuncionarios() {
        cbxFuncionarios.removeAllItems();
        Funcionario funcionario1 = new Funcionario();
        funcionario1.setNombre(SELECCIONE);
        funcionario1.setApellido("");
        cbxFuncionarios.addItem(funcionario1);
        tblFuncionarios.removeAll();

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }
        tblFuncionarios.setModel(defaultTableModel);

        try {
            List<Funcionario> funcionarios = funcionarios = funcionarioController.obtenerFuncionarios();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(funcionarios.size());
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaultTableModel.setValueAt(funcionario.getId_funcionario(), row, 0);
                defaultTableModel.setValueAt(funcionario.getNombre(), row, 1);
                defaultTableModel.setValueAt(funcionario.getApellido(), row, 2);
                defaultTableModel.setValueAt(funcionario.getTipo_identificacion(), row, 3);
                defaultTableModel.setValueAt(funcionario.getNum_documento(), row, 4);
                defaultTableModel.setValueAt(funcionario.getDireccion(), row, 5);
                defaultTableModel.setValueAt(funcionario.getSexo(), row, 6);
                defaultTableModel.setValueAt(funcionario.getTel(), row, 7);
                defaultTableModel.setValueAt(funcionario.getF_nacimiento(), row, 8);
                defaultTableModel.setValueAt(funcionario.getNivel_educativo(), row, 9);
                row++;

                cbxFuncionarios.addItem(funcionario);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    private void addListener() {
        cbxFuncionarios.addItemListener(event -> {
            Funcionario selectedFuncionario = (Funcionario) event.getItem();
            if (selectedFuncionario.getNombre().equals(SELECCIONE)) {
                txtFuncionarioId.setText("");
                txtNombreEdit.setText("");
                txtApellidoEdit.setText("");
                txtTipoEdit.setText("");
                txtNumeroEdit.setText("");
                txtDireccionEdit.setText("");
                txtSexoEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFechaEdit.setText("");
                txtNivelEdit.setText("");

            } else {
                txtFuncionarioId.setText(String.valueOf(selectedFuncionario.getId_funcionario()));
                txtNombreEdit.setText(selectedFuncionario.getNombre());
                txtApellidoEdit.setText(selectedFuncionario.getApellido());
                txtTipoEdit.setText(selectedFuncionario.getTipo_identificacion());
                txtNumeroEdit.setText(String.valueOf(selectedFuncionario.getNum_documento()));
                txtDireccionEdit.setText(selectedFuncionario.getDireccion());
                txtSexoEdit.setText(selectedFuncionario.getSexo());
                txtTelefonoEdit.setText(String.valueOf(selectedFuncionario.getTel()));
                txtFechaEdit.setText(String.valueOf(selectedFuncionario.getF_nacimiento()));
                txtNivelEdit.setText(String.valueOf(selectedFuncionario.getNivel_educativo()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTPanels = new javax.swing.JTabbedPane();
        jPFuncionario = new javax.swing.JPanel();
        jPFuncionario1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cbxNivel = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        cbxTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPEdit = new javax.swing.JPanel();
        lblFuncionarios = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        lblFuncionarioId = new javax.swing.JLabel();
        lblNombreEdit = new javax.swing.JLabel();
        lblApellidoEdit = new javax.swing.JLabel();
        lblTipoEdit = new javax.swing.JLabel();
        lblNumeroEdit = new javax.swing.JLabel();
        lblDireccionEdit = new javax.swing.JLabel();
        lblSexoEdit = new javax.swing.JLabel();
        lblFechaEdit = new javax.swing.JLabel();
        lblTelefonoEdit = new javax.swing.JLabel();
        lblNivelEdit = new javax.swing.JLabel();
        txtFuncionarioId = new javax.swing.JTextField();
        txtNombreEdit = new javax.swing.JTextField();
        txtApellidoEdit = new javax.swing.JTextField();
        txtTipoEdit = new javax.swing.JTextField();
        txtNumeroEdit = new javax.swing.JTextField();
        txtDireccionEdit = new javax.swing.JTextField();
        txtFechaEdit = new javax.swing.JTextField();
        txtTelefonoEdit = new javax.swing.JTextField();
        txtNivelEdit = new javax.swing.JTextField();
        txtSexoEdit = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GESTION FUNCIONARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jPFuncionario1.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguientes campos"));

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblTipo.setText("Tipo de documento");

        lblNumero.setText("Numero de documento");

        lblDireccion.setText("Direccion");

        lblSexo.setText("Sexo");

        lblFecha.setText("Fecha de nacimiento");

        lblTelefono.setText("Telefono");

        lblNivel.setText("Nivel educativo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Tecnico", "Tecnologo", "Profesional" }));

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino", "Otro" }));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "CC", "CE", "TI" }));

        javax.swing.GroupLayout jPFuncionario1Layout = new javax.swing.GroupLayout(jPFuncionario1);
        jPFuncionario1.setLayout(jPFuncionario1Layout);
        jPFuncionario1Layout.setHorizontalGroup(
            jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addGroup(jPFuncionario1Layout.createSequentialGroup()
                        .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(486, 486, 486)
                        .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNivel)
                                .addComponent(lblTelefono)
                                .addComponent(lblFecha)
                                .addComponent(lblSexo)
                                .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtTelefono))
                            .addComponent(btnGuardar)
                            .addComponent(cbxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPFuncionario1Layout.setVerticalGroup(
            jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPFuncionario1Layout.createSequentialGroup()
                        .addComponent(lblDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout jPFuncionarioLayout = new javax.swing.GroupLayout(jPFuncionario);
        jPFuncionario.setLayout(jPFuncionarioLayout);
        jPFuncionarioLayout.setHorizontalGroup(
            jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarioLayout.createSequentialGroup()
                .addGroup(jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFuncionario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPFuncionarioLayout.setVerticalGroup(
            jPFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTPanels.addTab("Crear funcionario", jPFuncionario);

        jPEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos"));

        lblFuncionarios.setText("Funcionarios");

        lblFuncionarioId.setText("Id funcionario");

        lblNombreEdit.setText("Nombre");

        lblApellidoEdit.setText("Apellido");

        lblTipoEdit.setText("Tipo de documento");

        lblNumeroEdit.setText("Numero de documento");

        lblDireccionEdit.setText("Direccion");

        lblSexoEdit.setText("Sexo");

        lblFechaEdit.setText("Fecha de nacimiento");

        lblTelefonoEdit.setText("Telefono");

        lblNivelEdit.setText("Nivel educativo");

        txtSexoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoEditActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEditLayout = new javax.swing.GroupLayout(jPEdit);
        jPEdit.setLayout(jPEditLayout);
        jPEditLayout.setHorizontalGroup(
            jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditLayout.createSequentialGroup()
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEditLayout.createSequentialGroup()
                        .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPEditLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombreEdit)
                                        .addComponent(lblApellidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTipoEdit)
                                        .addComponent(lblNumeroEdit)
                                        .addComponent(lblFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtApellidoEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTipoEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumeroEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(232, 232, 232)
                        .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSexoEdit)
                                .addComponent(lblFechaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccionEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtFechaEdit)
                                .addComponent(txtTelefonoEdit)
                                .addComponent(txtNivelEdit)
                                .addComponent(txtSexoEdit))
                            .addComponent(lblNivelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuncionarios)
                            .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPEditLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnActualizar)
                        .addGap(109, 109, 109)
                        .addComponent(btnEliminar)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPEditLayout.setVerticalGroup(
            jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionarioId)
                    .addComponent(lblDireccionEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEdit)
                    .addComponent(lblSexoEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoEdit)
                    .addComponent(lblFechaEdit))
                .addGap(7, 7, 7)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEdit)
                    .addComponent(lblTelefonoEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroEdit)
                    .addComponent(lblNivelEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNivelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTPanels.addTab("Editar funcionario", jPanel2);

        getContentPane().add(JTPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1030, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNombre.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite nombre");
            txtNombre.requestFocus();
            return;
        }

        if (txtApellido.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite apellido");
            txtApellido.requestFocus();
            return;
        }

        //if (txtTipo.getText().trim().length() == 0) {
        String opcion = cbxTipo.getSelectedItem().toString();
        if (opcion.equals("Seleccione")) {
            JOptionPane.showMessageDialog(null, "Digite Tipo de documento");
            cbxTipo.requestFocus();
            return;
        }

        if (txtNumero.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el numero de documento");
            txtNumero.requestFocus();
            return;
        }

        if (txtDireccion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la direccion");
            txtDireccion.requestFocus();
            return;
        }

        // if (txtSexo.getText().trim().length() == 0) {
        String opcion1 = cbxSexo.getSelectedItem().toString();
        if (opcion.equals("Seleccione")) {
            JOptionPane.showMessageDialog(null, "Digite el sexo");
            cbxSexo.requestFocus();
            return;
        }

        if (txtTelefono.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el telefono");
            txtTelefono.requestFocus();
            return;
        }

        if (txtFecha.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la fecha de nacimiento");
            txtFecha.requestFocus();
            return;
        }

        //if (txtNive1.getText().trim().length() == 0) {
        String opcion2 = cbxNivel.getSelectedItem().toString();
        if (opcion.equals("Seleccione")) {
            JOptionPane.showMessageDialog(null, "Digite el nivel educativo");
            cbxNivel.requestFocus();
            return;
        }

        Funcionario funcionario = new Funcionario();
        funcionario.setNombre(txtNombre.getText().trim());
        funcionario.setApellido(txtApellido.getText().trim());
        //funcionario.setTipo_identificacion(txtTipo.getText().trim());
        funcionario.setTipo_identificacion(String.valueOf(cbxTipo.getSelectedItem()));
        funcionario.setNum_documento(Integer.parseInt(txtNumero.getText().trim()));
        funcionario.setDireccion(txtDireccion.getText().trim());
        //funcionario.setSexo(txtSexo.getText().trim());
        funcionario.setSexo(String.valueOf(cbxSexo.getSelectedItem()));
        funcionario.setTel(Integer.parseInt((txtTelefono.getText().trim())));
        funcionario.setF_nacimiento(txtFecha.getText().trim());
        //funcionario.setNivel_educativo((txtNombre.getText().trim()));
        funcionario.setNivel_educativo(String.valueOf(cbxNivel.getSelectedItem()));

        try {
            funcionarioController.crear(funcionario);
            txtNombre.setText("");
            txtApellido.setText("");
            //cbxTipo.setSe("");
            txtNumero.setText("");
            txtDireccion.setText("");
            //cbxSexo.setText("");
            txtTelefono.setText("");
            txtFecha.setText("");
            //txtNivel1.setText("");
            listFuncionarios();
            JOptionPane.showMessageDialog(null, "Funcionario creado con éxito");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Funcionario no pudo ser creado con éxito");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:

        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un funcionario de la lista");
            txtFuncionarioId.requestFocus();
            return;
        }

        if (txtNombreEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite un nombre");
            txtNombreEdit.requestFocus();
            return;
        }

        if (txtApellidoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite un apellido");
            txtApellidoEdit.requestFocus();
            return;
        }

        if (txtTipoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite un tpo de documento");
            txtTipoEdit.requestFocus();
            return;
        }

        if (txtNumeroEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite un numero de documento");
            txtNumeroEdit.requestFocus();
            return;
        }

        if (txtDireccionEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite una direccion");
            txtDireccionEdit.requestFocus();
            return;
        }

        if (txtSexoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el sexo");
            txtSexoEdit.requestFocus();
            return;
        }

        if (txtTelefonoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el sexo");
            txtTelefonoEdit.requestFocus();
            return;
        }

        if (txtFechaEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite una fecha");
            txtFechaEdit.requestFocus();
            return;
        }

        if (txtNivelEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite un nivel");
            txtNivelEdit.requestFocus();
            return;
        }

        Funcionario funcionario = new Funcionario();
        funcionario.setNombre(txtNombreEdit.getText().trim());
        funcionario.setApellido(txtApellidoEdit.getText().trim());
        funcionario.setTipo_identificacion(txtTipoEdit.getText().trim());
        funcionario.setNum_documento(Integer.parseInt((txtNumeroEdit.getText().trim())));
        funcionario.setDireccion(txtDireccionEdit.getText().trim());
        funcionario.setSexo(txtSexoEdit.getText().trim());
        funcionario.setTel(Integer.parseInt(txtTelefonoEdit.getText().trim()));
        funcionario.setF_nacimiento(txtFechaEdit.getText().trim());
        funcionario.setNivel_educativo(txtNivelEdit.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el funcionario", "Confirmar Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funcionarioController.actualizarFuncionario(Integer.parseInt(txtFuncionarioId.getText()), funcionario);
                txtFuncionarioId.setText("");
                txtNombreEdit.setText("");
                txtApellidoEdit.setText("");
                txtTipoEdit.setText("");
                txtNumeroEdit.setText("");
                txtDireccionEdit.setText("");
                txtSexoEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFechaEdit.setText("");
                txtNivelEdit.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Se ha actualizado el funcionario con exito");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No fue posible actualizar el funcionario con exito");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un funcionario de la lista");
            txtFuncionarioId.requestFocus();
            return;
        }

        int opt = JOptionPane.showConfirmDialog(null, "Está seguro de borrar funcionario", "Confirmar Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funcionarioController.eliminarFuncionario(Integer.parseInt(txtFuncionarioId.getText()));
                txtFuncionarioId.setText("");
                txtNombreEdit.setText("");
                txtApellidoEdit.setText("");
                txtTipoEdit.setText("");
                txtNumeroEdit.setText("");
                txtDireccionEdit.setText("");
                txtSexoEdit.setText("");
                txtTelefonoEdit.setText("");
                txtFechaEdit.setText("");
                txtNivelEdit.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Se ha eliminado el funcionario con exito");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el funcionario");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtSexoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTPanels;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Funcionario> cbxFuncionarios;
    private javax.swing.JComboBox<String> cbxNivel;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPEdit;
    private javax.swing.JPanel jPFuncionario;
    private javax.swing.JPanel jPFuncionario1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellidoEdit;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionEdit;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaEdit;
    private javax.swing.JLabel lblFuncionarioId;
    private javax.swing.JLabel lblFuncionarios;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelEdit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEdit;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroEdit;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSexoEdit;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoEdit;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoEdit;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoEdit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEdit;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaEdit;
    private javax.swing.JTextField txtFuncionarioId;
    private javax.swing.JTextField txtNivelEdit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEdit;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroEdit;
    private javax.swing.JTextField txtSexoEdit;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEdit;
    private javax.swing.JTextField txtTipoEdit;
    // End of variables declaration//GEN-END:variables

}
